export const tagColors = [
  { className: "bg-jaffa", hex: "#e47947" },
  { className: "bg-mikdado-yellow", hex: "#f9c80c" },
  { className: "bg-lavender-indigo", hex: "#8d51ff" },
  { className: "bg-amaranth", hex: "#e93546" },
  { className: "bg-dullCyan", hex: "#44bbcd" },
  { className: "bg-aquamarine-blue", hex: "#71e6d4" },
  { className: "bg-fern", hex: "#70ad6e" },
  { className: "bg-eerie-Black", hex: "#beed63" },
  { className: "bg-green-mist", hex: "#c5c393" },
  { className: "bg-sasquatch-socks", hex: "#ff4d7f" },
  { className: "bg-wedgewood", hex: "#4c688e" },
  { className: "bg-sea-pink", hex: "#e37f7c" },
  { className: "bg-tundara", hex: "#483c46" },
  { className: "bg-rose-bud", hex: "#f5a698" },
  { className: "bg-ash-gray", hex: "#b4c2b8" },
  { className: "bg-oracle", hex: "#3c6e71" },
  { className: "bg-camelot", hex: "#883a55" },
];
